#!/bin/sh
# 
# Start apache in foreground
# 
# inspiration from: https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground 
set -e

#Ensure that permanent volumes are correctly set
#Keep TEITOK Scripts and Common updated by linking them to /usr/local/src/TEITOK
if [ ! -d "/var/www/html/TEITOK" ]; then
mkdir -p /var/www/html/TEITOK
ln -s /usr/local/src/TEITOK/Scripts /var/www/html/TEITOK/Scripts
ln -s /usr/local/src/TEITOK/Common /var/www/html/TEITOK/Common
cp -rvp /usr/local/src/TEITOK/myproject /var/www/html/TEITOK/
fi

#/var/www/html, where teitok sits
chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} /var/www/html

# Apache gets grumpy about PID files pre-existing
rm -f ${APACHE_PID_FILE}

exec apache2 -DFOREGROUND
