#!/bin/sh
# 
# Start apache in foreground
# 
# inspiration from: https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground 
set -e

#Ensure that permanent volumes are correctly set
if [ ! -d "/var/www/html/TEITOK" ]; then
mkdir -p /var/www/html/TEITOK
ln -s /usr/local/src/TEITOK/common /var/www/html/TEITOK/common
cp -rvp /usr/local/src/TEITOK/check /var/www/html/TEITOK/
cp -rvp /usr/local/src/TEITOK/projects /var/www/html/TEITOK/
fi


#Update apache2 configuration
if [ -f "/conf/apache2.conf" ]; then
cp /conf/apache2.conf /etc/apache2/
fi

#/var/www/html, where teitok sits
chown -R ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} /var/www/html

# Apache gets grumpy about PID files pre-existing
rm -f ${APACHE_PID_FILE}

exec apache2 -DFOREGROUND
